### ISSUE TITLE
Allow `pip install --no-binary` to work

### ISSUE THREAD

**Issue by bbayles** [ada-url/ada-python#49]
Noted in https://github.com/ada-url/ada-python/pull/46:
> `pip install ada_url --no-binary ada_url` will fail (on both Linux and Windows) because of the absence of `ada.o`

We would need to move the step that builds `ada.o` into the `python -m build` step. I looked into doing previously, but couldn't figure out a portable method.

**Comment by Master-Hash** [comment]
use `sources=['ada_url/ada.cpp']` (docs: https://setuptools.pypa.io/en/latest/userguide/ext_modules.html, https://cffi.readthedocs.io/en/stable/cdef.html#ffibuilder-set-source-preparing-out-of-line-modules) will not pass the CI.

Why It pass locally: local gcc version is 13, which defaults to `-std=gnu++17`.
But I don't know how to set different std for C and CPP.

**Comment by bbayles** [comment]
Perhaps we could build the `ada.o` file separately, include it in the source repo, and use `extra_objects` to link against it.

**Comment by bbayles** [comment]
Actually, I'm puzzled because `ada.o` is already in the `.tar.gz` source distribution file. So maybe the issue is making sure the linker can find it.

**Comment by bbayles** [comment]
Oh, but that's not cross platform. Never mind.
