### ISSUE TITLE
Set up ReadTheDocs

### ISSUE THREAD

**Issue by bbayles** [ada-url/ada-python#9]
I'd like to get https://readthedocs.org/dashboard/ada-url/ working. I can set this up myself if granted access to the settings for this repo that would allow me to configure the GitHub/RTD integration.

Failing that, I could add existing repository admins to the RTD and have them set up the integration.

My branch [here](https://github.com/ada-url/ada-python/tree/docs-conf) should allow for RTD to install the library to allow the [inline docstrings](https://github.com/ada-url/ada-python/blob/docs-conf/ada_url/ada_adapter.py#L33-L74) to be rendered.

**Comment by anonrig** [comment]
Hey @bbayles, I've granted you admin privileges on the repository. Hope that helps.
